# See https://dotwhat.net/type/audio-music-files

AUDIO_FORMATS = {
    "3GA": "3GPP Audio File",
    "AA": "Audible Audio file",
    "AA3": "ATRAC3 Audio File",
    "AAC": "Advanced Audio Coding File",
    "AAX": "Audible Enhanced Audiobook",
    "ABC": "Musical Notation Language File",
    "AC3": "Dolby Digital Audio Codec 3 file format",
    "ACD": "Acid Project File",
    "ACD-ZIP": "Sony Acid Project File (Inc Embedded Data)",
    "ACM": "InterPlay ACM Audio file format",
    "ACT": "ADPCM Audio File",
    "ADG": "Ableton Device Group",
    "ADTS": "Audio Data Transport Stream file format",
    "AFC": "Mass Effect 2 Audio File",
    "AHX": "WinAHX Tracker Module",
    "AIF": "Audio Interchange File",
    "AIFC": "Audio Interchange File (Compressed)",
    "AIFF": "Audio Interchange File",
    "AL": "ALAW Format Sound",
    "AMR": "Adaptive Multi-Rate file format",
    "AMZ": "Amazon MP3 Downloader Download File",
    "AOB": "DVD-Audio Audio Object File",
    "APC": "Cryo APC Audio file format",
    "APE": "Monkeys Audio File",
    "APF": "Sony Ericsson Acoustics Settings File",
    "ATRAC": "Sony ATRAC Audio File",
    "AU": "Sun Audio File Format",
    "AVR": "Audio Visual Research file",
    "AWB": "Compressed Speech Audio File",
    "BAP": "Blaze Audio Wave Information File",
    "BMW": "BuzzPlay music with waves",
    "CAF": "Core Audio File",
    "CDA": "CD Audio Track Shortcut",
    "CFA": "Conformed Audio File",
    "CIDB": "iTunes CD Information File",
    "COPY": "Sony Ericsson Protected Content File",
    "CPR": "Cubase Project File",
    "CWP": "Cakewalk SONAR Project",
    "DAC": "DAC Sound File",
    "DCF": "DRM Content Format File",
    "DCM": "DCM Audio Module",
    "DCT": "Dictation Audio File",
    "DFC": "Defractor Instrument",
    "DIG": "Sound Designer Audio File",
    "DSM": "Digital Sound Module",
    "DSS": "Digital Speech Standard File",
    "DTS": "Audio File Format",
    "DTSHD": "DTS-HD Master Audio",
    "DVF": "Sony Compressed Audio Format File",
    "EFA": "Ensoniq ASR file",
    "EFE": "Ensoniq EPS file",
    "EFK": "Ensoniq KT file",
    "EFV": "Ensoniq VFX-SD file",
    "EMD": "ABT Extended MoDule",
    "EMX": "eMusic Download Manager Download file format",
    "ENC": "Encore Musical Notation",
    "F64": "Raw 64-Bit Audio File",
    "FL": "Floating Sound Format",
    "FLAC": "Free Lossless Audio Codec File",
    "FLP": "Fruity Loops Project File",
    "FST": "Studio State File",
    "G726": "G.726 Audio File",
    "GNT": "Letter-Art File",
    "GPX": "Guitar Pro 6 Document file format",
    "GSM": "Audio stream Raw GSM/eFax Messenger Plus Voice Message",
    "HMA": "Sony Connect (SonicStage) Audio File",
    "HTW": "Hauptwerk Sound-font",
    "IFF": "Interchange File Format",
    "IKLAX": "iKlax Multi-Track Audio",
    "IMW": "IncrediMail MIDI/WAV",
    "IMY": "Ringtone File",
    "ITS": "Impulse Tracker Sample",
    "IVC": "Intervoice Audio File",
    "K26": "Kurzweil K2600 File",
    "KAR": "Karaoke MIDI File",
    "KFN": "Audio File",
    "KOE": "AquesTone Vocal Synthesiser Syllable File",
    "KOZ": "Audiokoz Music File/Bell Music File",
    "KPL": "Kazaa Playlist File",
    "KTP": "Kinetic Project Template",
    "LQT": "Liquid Audio Music File",
    "LVP": "Avaya Voice Player - Compressed Voice Audio File",
    "M3U": "Media Playlist File",
    "M3U8": "MP3 Playlist File (UTF-8)",
    "M4A": "MPEG-4 Audio Layer",
    "M4B": "MPEG-4 Audio Book File",
    "M4P": "iTunes Audio Format",
    "M4R": "MPEG-4 Ringtone file format",
    "MA1": "Monarch Audio File",
    "MID": "Musical Instrument Digital Interface (MIDI) Sound File",
    "MIDI": "Musical Instrument Digital Interface (MIDI) Sound File",
    "MINIUSF": "Nintendo 64 Song File",
    "MIO": "MIO Compressed Audio",
    "MKA": "Matroska Audio file format",
    "MMF": "Mobile Music File",
    "MON": "Wavelab Audio Montage File",
    "MP2": "MPEG Audio Stream",
    "MP3": "MP3 Audio File",
    "MPA": "MPEG Audio Stream",
    "MPC": "Musepack Audio File",
    "MPU": "MPEG Layer 3 Audio File",
    "MP_": "Mobile Phone Sound File",
    "MSV": "Sony Memory Stick Compressed Voice File",
    "MT2": "MadTracker 2 Module",
    "MTE": "MadTracker 2 Envelope",
    "MTP": "MadTracker 2 Pattern",
    "MUP": "Music Publisher File",
    "MXP4": "Musinaut Audio",
    "MZP": "Mozart Percussion File",
    "NCOR": "Adobe Encore Project File",
    "NKI": "KONTAKT Instrument File",
    "NRT": "Nokia RingTone",
    "NSA": "Nullsoft Streaming Audio File",
    "NTN": "NOTION Song File",
    "NWC": "Noteworthy Composer Song File",
    "ODM": "OverDrive Media File",
    "OGA": "Ogg Vorbis Audio",
    "OGG": "Ogg Vorbis Codec Compressed WAV File",
    "OMA": "Sony OpenMG Audio File",
    "OMG": "OpenMG Audio File",
    "OMX": "OtsAV Media Library Information File",
    "OTS": "OtsAV Album File",
    "OVE": "Cakewalk Overture Score",
    "PCAST": "iTunes Podcast file format",
    "PEK": "Adobe Peak Waveform File",
    "PLA": "Playlist File",
    "PLS": "PlayList File",
    "PNA": "PhatNoise Audio File",
    "PROG": "Cakewalk Sonar Beatscape Preset Program File",
    "PVC": "Panasonic VM1 Voice File",
    "QCP": "Voice File",
    "R1M": "RealOne Streaming Media File",
    "RA": "RealMedia Streaming Audio File",
    "RAM": "RealMedia Metafile",
    "RAW": "Raw Audio File Format",
    "RAX": "Real Music Store Audio File",
    "REX": "Audio Sample File",
    "RFL": "Reason ReFill Sound Bank",
    "RIF": "Audio File in WAV format",
    "RMJ": "Real Media Jukebox Audio File",
    "RNS": "Reason Song File",
    "RSD": "Roland Sound File",
    "RSO": "NXT Brick Audio File",
    "RTI": "Real Tracker Instrument",
    "RX2": "REX2 Loop File",
    "SA1": "Audio Encryption File",
    "SBR": "Spectral Band Replication Audio Sound File",
    "SD2": "Sound Designer 2 Flattened File / Data Fork",
    "SFA": "Sound Forge Audio File",
    "SGT": "Microsoft DirectMusic Producer Segments File",
    "SID": "PlaySID C64 Sound Effects File",
    "SMF": "Standard Midi File",
    "SND": "Apple Sound Resource File",
    "SNG": "Midi song file",
    "SNS": "Burnout Paradise Sound File",
    "SPRG": "Synclavier Program File",
    "SSEQ": "Synclavier Sequence File",
    "SSND": "Synclavier Sound File",
    "SWA": "ShockWave Audio",
    "SYH": "Synchomatic Instrument",
    "SZ": "Winamp Classic Skin Download",
    "TAP": "Wave Sound or Action Wave",
    "TRM": "For The Record Voice Recording File",
    "UL": "Audio file",
    "USF": "Nintendo 64 Music File",
    "USFLIB": "Nintendo 64 Song Library",
    "USM": "Unsigned Sample Module data Farandole",
    "VAG": "Sony PlayStation ADPCM Sound File",
    "VMO": "Siemens Mobile Phone Voice File",
    "VOI": "Voyetra Voice File",
    "VOX": "Dialogic Voice File",
    "VPM": "Garmin GPS Navigation Voice File",
    "VRF": "Ventrilo Audio Recording",
    "VY1": "VY3 ETC - Audio Footage File",
    "VYF": "Samsung Digital Voice Recorder File",
    "W01": "Yamaha SY Series Wave File",
    "W64": "Wave64 File",
    "WAV": "Waveform Audio",
    "WMA": "Windows Media Audio File",
    "WPROJ": "Wwise Project",
    "WRK": "CakeWalk Project file",
    "WUS": "WUTG Tagged Audio File",
    "WUT": "WUTG Tag File",
    "WWU": "Wwise Work Unit",
    "XFS": "eRacer Sound File",
    "ZGR": "BeatCreator Loop File",
    "ZVR": "SAFA Audio Recording File",
}
